server {
    listen 3000;

    location /api/ {
        proxy_pass http://api-gateway:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Cache-Control "no-store";
    }

    location = /index.html {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-store";
    }

    location /assets/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        add_header Cache-Control "no-cache";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }
}
